comment:
  layout: "diff, flags, files"

flags:
  statetests:
    paths:
      - lib/zvmone
      - test/state
      - test/statetest
  blockchaintests:
    joined: false
    paths:
      - lib/zvmone
